#!/usr/bin/env node

/**
 * Generates a clean, professional cover letter PDF from a Markdown file.
 *
 * Design: Minimal header (name + thin accent rule + contact line),
 * well-spaced body paragraphs, clean signature. No sidebar, no boxes.
 * Inspired by Awesome CV cover letter style.
 *
 * Usage:
 *   node scripts/generate-letter.mjs letter-padoa.md
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname, basename } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT = resolve(__dirname, '..');

const args = process.argv.slice(2);
if (args.length === 0) {
  console.error('Usage: node scripts/generate-letter.mjs <letter.md>');
  process.exit(1);
}

const mdFile = resolve(ROOT, args[0]);
if (!existsSync(mdFile)) {
  console.error(`File not found: ${mdFile}`);
  process.exit(1);
}

function tex(str) {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

function parseLetter(mdContent) {
  const lines = mdContent.trim().split('\n');
  const paragraphs = [];
  let greeting = '';
  let closing = '';
  let signature = [];
  let currentParagraph = [];
  let foundClosing = false;

  for (const line of lines) {
    const trimmed = line.trim();

    if (!greeting && /^(Bonjour|Dear|Madame|Monsieur|Hello)/i.test(trimmed)) {
      greeting = trimmed;
      continue;
    }

    if (/^(Cordialement|Sincerely|Best regards|Kind regards|Bien à vous)/i.test(trimmed)) {
      if (currentParagraph.length > 0) {
        paragraphs.push(currentParagraph.join(' '));
        currentParagraph = [];
      }
      closing = trimmed;
      foundClosing = true;
      continue;
    }

    if (foundClosing) {
      if (trimmed) signature.push(trimmed);
      continue;
    }

    if (trimmed === '') {
      if (currentParagraph.length > 0) {
        paragraphs.push(currentParagraph.join(' '));
        currentParagraph = [];
      }
    } else {
      currentParagraph.push(trimmed);
    }
  }

  if (currentParagraph.length > 0) {
    paragraphs.push(currentParagraph.join(' '));
  }

  return { greeting, paragraphs, closing, signature };
}

function generateLetterLatex(letter) {
  const bodyParagraphs = letter.paragraphs
    .map((p) => tex(p))
    .join('\n\n');

  const sigParts = [];
  for (const s of letter.signature) {
    if (s.includes('|')) {
      const parts = s.split('|').map((x) => x.trim());
      const formatted = parts.map((part) => {
        if (part.includes('@')) return `\\href{mailto:${part}}{\\color{mutedtext}${tex(part)}}`;
        if (part.match(/^[a-z-]+\.[a-z]+/i)) return `\\href{https://${part}}{\\color{mutedtext}${tex(part)}}`;
        if (part.startsWith('+')) return `\\color{mutedtext}${tex(part)}`;
        return `\\color{mutedtext}${tex(part)}`;
      });
      sigParts.push(`{\\small ${formatted.join('\\hspace{6pt}{\\color{sep}\\textbar}\\hspace{6pt}')}}`);
    } else if (s.includes(':')) {
      const [label, value] = s.split(':').map((x) => x.trim());
      if (value && value.includes('@')) {
        sigParts.push(`{\\small\\color{mutedtext}${tex(label)} : \\href{mailto:${value}}{${tex(value)}}}`);
      } else if (value && value.match(/[a-z-]+\.[a-z]/i)) {
        const url = value.startsWith('http') ? value : `https://${value}`;
        sigParts.push(`{\\small\\color{mutedtext}${tex(label)} : \\href{${url}}{${tex(value)}}}`);
      } else {
        sigParts.push(`{\\small\\color{mutedtext}${tex(s)}}`);
      }
    } else if (s === s.toUpperCase() && s.length > 3) {
      sigParts.push(`{\\color{titletext}\\textbf{${tex(s)}}}`);
    } else {
      sigParts.push(`{\\small\\color{mutedtext}${tex(s)}}`);
    }
  }

  const signatureBlock = sigParts.join('\\\\[1.5pt]\n');

  return `%% Cover Letter — generated by generate-letter.mjs

\\documentclass[a4paper, 10.5pt]{article}
\\usepackage[top=28mm, bottom=24mm, left=28mm, right=28mm]{geometry}
\\usepackage{xcolor}
\\usepackage{tikz}
\\usepackage[hidelinks]{hyperref}
\\usepackage[french]{babel}
\\usepackage[T1]{fontenc}
\\usepackage[sfdefault]{inter}
\\usepackage{raleway}
\\usepackage{parskip}

\\pagestyle{empty}
\\setlength{\\parindent}{0pt}
\\setlength{\\parskip}{7pt}

\\tolerance=200
\\emergencystretch=2em

\\newcommand{\\headingfont}{\\fontfamily{Raleway-TLF}\\selectfont}

% Colors
\\definecolor{accent}{HTML}{B5651D}
\\definecolor{titletext}{HTML}{111827}
\\definecolor{bodytext}{HTML}{374151}
\\definecolor{mutedtext}{HTML}{6B7280}
\\definecolor{sep}{HTML}{D1D5DB}
\\definecolor{rulecolor}{HTML}{E5E7EB}

\\begin{document}
\\color{bodytext}

% ─── Header ──────────────────────────────────────────────────────────────────
\\begin{center}
{\\headingfont\\fontsize{20}{24}\\selectfont\\bfseries\\color{titletext}Amaury Dufrenot}\\\\[4pt]
{\\small\\color{mutedtext}Étudiant ingénieur Réseaux \\& Télécommunications — UTT}\\\\[6pt]
{\\small\\color{mutedtext}\\href{mailto:amaury.dufrenot@utt.fr}{amaury.dufrenot@utt.fr}\\hspace{6pt}{\\color{sep}\\textbar}\\hspace{6pt}+33 6 44 19 68 50\\hspace{6pt}{\\color{sep}\\textbar}\\hspace{6pt}\\href{https://amaury-dufrenot.me}{amaury-dufrenot.me}}\\\\[8pt]
{\\color{accent}\\rule{0.35\\textwidth}{0.8pt}}
\\end{center}

\\vspace{6mm}

% ─── Body ────────────────────────────────────────────────────────────────────
${tex(letter.greeting)}

${bodyParagraphs}

\\vspace{2mm}

${tex(letter.closing)}

\\vspace{3mm}
${signatureBlock}

\\end{document}
`;
}

async function main() {
  const mdContent = readFileSync(mdFile, 'utf-8');
  const letter = parseLetter(mdContent);

  const outDir = resolve(ROOT, 'public', 'letters');
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });

  const texDir = resolve(ROOT, 'letter-output');
  if (!existsSync(texDir)) mkdirSync(texDir, { recursive: true });

  const stem = basename(mdFile, '.md');
  const texPath = resolve(texDir, `${stem}.tex`);

  console.log(`\n--- Generating cover letter PDF ---`);
  console.log(`  Source: ${mdFile}`);

  const latexContent = generateLetterLatex(letter);
  writeFileSync(texPath, latexContent, 'utf-8');
  console.log(`  .tex saved: ${texPath}`);

  try {
    const { compile } = await import('node-latex-compiler');

    console.log(`  Compiling to PDF (Tectonic)...`);
    const result = await compile({
      texFile: texPath,
      outputDir: outDir,
      onStdout: (data) => {
        const trimmed = data.trim();
        if (trimmed) console.log(`  [tectonic] ${trimmed}`);
      },
      onStderr: (data) => {
        const trimmed = data.trim();
        if (trimmed) console.log(`  [tectonic] ${trimmed}`);
      },
    });

    if (result.status === 'success') {
      console.log(`  PDF generated: ${result.pdfPath}`);
    } else {
      console.error(`  Compilation failed: ${result.error || result.stderr}`);
      console.log(`  .tex file is still available at: ${texPath}`);
    }
  } catch (err) {
    console.error(`  node-latex-compiler error: ${err.message}`);
    console.log(`  .tex file is still available at: ${texPath}`);
  }

  console.log('\nDone!');
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
